general:                  
steps: 
 gctsDeploy:
   host: 'https://s4hana2021.clebaltech.com:8010'
   client: '200'
   abapCredentialsId: 'ADITYA_CREDENTIALS'
   repository: 'adtygpt-adtygpt'
   remoteRepositoryURL: "https://github.com/adtygpt/adtygpt"
   role: 'PROVIDED'
   vSID: 'DEV'
   branch: 'bugfix'
    commit: 'c1002ed'
    scope: 'CRNTCOMMIT'
    rollback: false
    configuration:
        VCS_AUTOMATIC_PULL: "FALSE"
        VCS_AUTOMATIC_PUSH: "FALSE"
        CLIENT_VCS_LOGLVL: "debug"
